# Generated by Django 3.2.8 on 2021-10-30 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('plugged_number', models.CharField(max_length=55, primary_key=True, serialize=False)),
                ('driver', models.CharField(max_length=100)),
                ('type', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('production_date', models.DateField(blank=True)),
                ('registration_date', models.DateField(blank=True)),
                ('is_cross_out', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(max_length=255)),
                ('tax', models.DecimalField(decimal_places=3, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleViolationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True)),
                ('location', models.CharField(max_length=255)),
                ('is_paid', models.BooleanField(default=False)),
                ('plugged_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vehicle')),
                ('violations_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.violation')),
            ],
        ),
    ]
