# Generated by Django 3.2.8 on 2021-10-30 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleviolationlog',
            name='plugged_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='api.vehicle'),
        ),
        migrations.AlterField(
            model_name='vehicleviolationlog',
            name='violations_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violation', to='api.violation'),
        ),
    ]
