# Generated by Django 3.2.8 on 2021-10-28 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicleslog',
            name='id',
        ),
        migrations.AlterField(
            model_name='vehicleslog',
            name='plugged_number',
            field=models.CharField(max_length=55, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='violationlog',
            name='date',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
